// newsradar_front/src/app/UI/features/noticias/components/vigilancia/subscription-form.component.ts
import { Component, inject, input, output, signal } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { VIGILANCIA_API } from '../../../../../infrastructure/noticias/services/noticias-api.token';
import { TopicItem } from '../../../../../domain/noticias/models';

@Component({
  selector: 'app-subscription-form',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <form [formGroup]="form" (ngSubmit)="onSubmit()" aria-label="Suscripción a vigilancia tecnológica">
      <fieldset>
        <legend class="text-sm font-semibold mb-3">Datos del suscriptor</legend>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label for="vigilancia-email" class="block text-sm mb-1">Email</label>
            <input id="vigilancia-email" type="email" formControlName="email"
              class="w-full border rounded px-3 py-2 text-sm" placeholder="usuario&#64;empresa.com" />
            @if (form.get('email')?.touched && form.get('email')?.invalid) {
              <p class="text-red-500 text-xs mt-1">Ingrese un email válido.</p>
            }
          </div>
          <div>
            <label for="vigilancia-name" class="block text-sm mb-1">Nombre</label>
            <input id="vigilancia-name" formControlName="name"
              class="w-full border rounded px-3 py-2 text-sm" placeholder="Nombre completo" />
            @if (form.get('name')?.touched && form.get('name')?.invalid) {
              <p class="text-red-500 text-xs mt-1">El nombre es obligatorio.</p>
            }
          </div>
        </div>
      </fieldset>

      <fieldset class="mt-4">
        <legend class="text-sm font-semibold mb-3">Temas de interés</legend>
        <div formArrayName="selectedGroups" class="space-y-1">
          @for (topic of topics(); track topic.group_id; let i = $index) {
            <label class="flex items-center gap-2 text-sm">
              <input type="checkbox" [formControlName]="i" />
              {{ topic.display_name }} ({{ topic.term_count }} términos)
            </label>
          }
        </div>
        @if (showGroupsError()) {
          <p class="text-red-500 text-xs mt-1">Seleccione al menos un tema.</p>
        }
      </fieldset>

      @if (error()) {
        <p class="text-red-600 text-sm mt-2" role="alert">{{ error() }}</p>
      }

      <button type="submit" [disabled]="loading()"
        class="mt-4 px-4 py-2 bg-yellow-400 text-black rounded text-sm font-medium disabled:opacity-50">
        @if (loading()) {
          Suscribiendo...
        } @else {
          Suscribirse
        }
      </button>
    </form>
  `,
})
export class SubscriptionFormComponent {
  private readonly api = inject(VIGILANCIA_API);
  private readonly fb = inject(FormBuilder);

  readonly topics = input<TopicItem[]>([]);
  readonly confirmation = output<string>();
  readonly loading = signal(false);
  readonly error = signal<string | null>(null);
  readonly showGroupsError = signal(false);

  readonly form: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    name: ['', Validators.required],
    selectedGroups: this.fb.array([]),
  });

  get groupsArray(): FormArray {
    return this.form.get('selectedGroups') as FormArray;
  }

  ngOnChanges(): void {
    const arr = this.groupsArray;
    arr.clear();
    for (const _ of this.topics()) {
      arr.push(this.fb.control(false));
    }
  }

  onSubmit(): void {
    this.form.markAllAsTouched();
    this.error.set(null);
    this.showGroupsError.set(false);

    const selectedIds = this.topics()
      .filter((_, i) => this.groupsArray.at(i).value)
      .map((t) => t.group_id);

    if (selectedIds.length === 0) {
      this.showGroupsError.set(true);
      return;
    }

    if (this.form.invalid) return;

    this.loading.set(true);

    this.api
      .subscribe({
        email: this.form.value.email,
        name: this.form.value.name,
        query_groups: selectedIds,
      })
      .subscribe({
        next: (res) => {
          this.confirmation.emit(
            `Suscripción exitosa para ${res.email}. Temas suscritos: ${res.subscribed_groups.join(', ')}`
          );
          this.loading.set(false);
        },
        error: (err) => {
          this.error.set(err.message ?? 'Error desconocido');
          this.loading.set(false);
        },
      });
  }
}

// newsradar_front/src/components/vigilancia/SubscriptionForm.tsx
/**
 * SubscriptionForm — Self-contained subscription form for Vigilancia Tecnológica.
 *
 * Loads available topics on mount via fetchTopics(), validates required fields
 * (email, name, at least one topic), submits via subscribe(), and shows
 * confirmation with email and subscribed topics on success.
 *
 * Validates: Req 4.1, 4.2, 4.3, 4.4, 4.5, 4.6
 */
import React, { useState, useEffect, useCallback, FormEvent } from "react";
import {
  fetchTopics,
  subscribe,
  type TopicItem,
  type SubscribeResponse,
} from "@/lib/api";

export default function SubscriptionForm() {
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [topics, setTopics] = useState<TopicItem[]>([]);
  const [topicsLoading, setTopicsLoading] = useState(true);
  const [topicsError, setTopicsError] = useState(false);
  const [selectedGroups, setSelectedGroups] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<SubscribeResponse | null>(null);

  const loadTopics = useCallback(async () => {
    setTopicsLoading(true);
    setTopicsError(false);
    setError(null);
    try {
      const data = await fetchTopics();
      setTopics(data.topics);
    } catch {
      setTopicsError(true);
      setError("No se pudieron cargar los temas disponibles.");
    } finally {
      setTopicsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadTopics();
  }, [loadTopics]);

  function toggleGroup(groupId: string) {
    setSelectedGroups((prev) =>
      prev.includes(groupId)
        ? prev.filter((g) => g !== groupId)
        : [...prev, groupId]
    );
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!email || !name || selectedGroups.length === 0) {
      setError("Complete todos los campos y seleccione al menos un tema.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const data = await subscribe({ email, name, query_groups: selectedGroups });
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error desconocido");
    } finally {
      setLoading(false);
    }
  }

  function resetForm() {
    setEmail("");
    setName("");
    setSelectedGroups([]);
    setResult(null);
    setError(null);
  }

  // ── Topics loading state ──
  if (topicsLoading) {
    return (
      <div data-testid="subscription-form" aria-label="Formulario de suscripción">
        <p>Cargando temas...</p>
      </div>
    );
  }

  // ── Topics load error with retry ──
  if (topicsError) {
    return (
      <div data-testid="subscription-form" aria-label="Formulario de suscripción">
        <p role="alert" style={{ color: "var(--color-error, red)" }}>
          {error}
        </p>
        <button type="button" onClick={loadTopics}>
          Reintentar
        </button>
      </div>
    );
  }

  // ── Success confirmation ──
  if (result) {
    return (
      <div data-testid="subscription-form" aria-label="Formulario de suscripción">
        <div data-testid="subscription-confirmation">
          <p>Suscripción exitosa para {result.email}.</p>
          <p>Temas suscritos: {result.subscribed_groups.join(", ")}</p>
          <button type="button" onClick={resetForm}>
            Nueva suscripción
          </button>
        </div>
      </div>
    );
  }

  // ── Subscription form ──
  return (
    <div data-testid="subscription-form" aria-label="Formulario de suscripción">
      <form onSubmit={handleSubmit} aria-label="Suscripción a vigilancia tecnológica">
        <fieldset>
          <legend>Datos del suscriptor</legend>

          <div className="form-grid">
            <div>
              <label htmlFor="vigilancia-email">Email</label>
              <input
                id="vigilancia-email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="usuario@empresa.com"
                required
              />
            </div>

            <div>
              <label htmlFor="vigilancia-name">Nombre</label>
              <input
                id="vigilancia-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Nombre completo"
                required
              />
            </div>
          </div>
        </fieldset>

        <fieldset style={{ marginTop: "var(--spacing-md, 16px)" }}>
          <legend>Temas de interés</legend>
          {topics.map((t) => (
            <label
              key={t.group_id}
              style={{ display: "block", marginBottom: "var(--spacing-xs, 4px)" }}
            >
              <input
                type="checkbox"
                checked={selectedGroups.includes(t.group_id)}
                onChange={() => toggleGroup(t.group_id)}
                aria-label={t.display_name}
              />
              {" "}{t.display_name} ({t.term_count} términos)
            </label>
          ))}
        </fieldset>

        <button
          type="submit"
          disabled={loading}
          style={{ marginTop: "var(--spacing-md, 12px)" }}
        >
          {loading ? "Suscribiendo..." : "Suscribirse"}
        </button>
      </form>

      {error && (
        <p
          role="alert"
          style={{ color: "var(--color-error, red)", marginTop: "var(--spacing-sm, 8px)" }}
          data-testid="subscription-error"
        >
          {error}
        </p>
      )}
    </div>
  );
}
