// newsradar_front/src/app/UI/features/noticias/components/riesgos/results-table.component.ts
import { Component, input, signal } from '@angular/core';
import { DocumentResult } from '../../../../../domain/noticias/models';

@Component({
  selector: 'app-results-table',
  standalone: true,
  template: `
    @if (results().length === 0) {
      <p class="text-gray-500 text-sm">Sin resultados para los criterios especificados.</p>
    } @else {
      <div class="overflow-auto rounded-lg shadow-sm">
        <table class="w-full text-sm border-collapse">
          <thead>
            <tr class="bg-gray-100 text-left">
              <th class="px-3 py-2">#</th>
              <th class="px-3 py-2">Título</th>
              <th class="px-3 py-2">Medio</th>
              <th class="px-3 py-2">Fecha</th>
              <th class="px-3 py-2">Categoría</th>
              <th class="px-3 py-2">Severidad</th>
              <th class="px-3 py-2">Confianza</th>
              <th class="px-3 py-2">Relevancia</th>
              <th class="px-3 py-2">Eventos</th>
              <th class="px-3 py-2">Evidencia</th>
              <th class="px-3 py-2">URL</th>
            </tr>
          </thead>
          <tbody>
            @for (doc of results(); track $index) {
              <tr class="border-b hover:bg-gray-50">
                <td class="px-3 py-2">{{ $index + 1 }}</td>
                <td class="px-3 py-2" data-field="title">{{ doc.title }}</td>
                <td class="px-3 py-2" data-field="source">{{ doc.source }}</td>
                <td class="px-3 py-2" data-field="date">{{ doc.published_at ?? '—' }}</td>
                <td class="px-3 py-2" data-field="category">{{ doc.category ?? '—' }}</td>
                <td class="px-3 py-2" data-field="severity">
                  <span [class]="severityBadgeClass(doc.severity)"
                    class="inline-block px-2 py-0.5 rounded text-xs font-bold">
                    {{ doc.severity ?? '—' }}
                  </span>
                </td>
                <td class="px-3 py-2" data-field="confidence">
                  @if (doc.confidence != null) {
                    {{ (doc.confidence * 100).toFixed(0) }}%
                  } @else {
                    —
                  }
                </td>
                <td class="px-3 py-2" data-field="relevance">
                  @if (doc.relevance_score != null) {
                    <div class="flex items-center gap-2">
                      <div class="w-20 bg-gray-200 rounded-full h-2">
                        <div class="h-2 rounded-full"
                          [class]="relevanceBarColor(doc.relevance_score)"
                          [style.width.%]="doc.relevance_score">
                        </div>
                      </div>
                      <span class="text-xs text-gray-600">{{ doc.relevance_score }}</span>
                    </div>
                  } @else {
                    —
                  }
                </td>
                <td class="px-3 py-2 max-w-[120px]" data-field="events">
                  @if (doc.events && doc.events.length > 0) {
                    <div class="flex flex-wrap gap-1">
                      @for (ev of doc.events.slice(0, 3); track ev) {
                        <span class="inline-block bg-orange-100 text-orange-800 text-xs px-1.5 py-0.5 rounded">
                          {{ ev }}
                        </span>
                      }
                    </div>
                  } @else {
                    —
                  }
                </td>
                <td class="px-3 py-2 max-w-xs" data-field="evidence">
                  @if (doc.evidence && doc.evidence.length > 0) {
                    <button (click)="toggleEvidence($index)"
                      class="text-blue-500 hover:underline text-xs">
                      {{ expandedRows().has($index) ? 'Ocultar' : 'Ver' }} ({{ doc.evidence.length }})
                    </button>
                    @if (expandedRows().has($index)) {
                      <div class="mt-1 text-xs text-gray-600 space-y-1">
                        @for (ev of doc.evidence.slice(0, 3); track $index) {
                          <p class="border-l-2 border-blue-300 pl-2">{{ ev }}</p>
                        }
                      </div>
                    }
                  } @else {
                    —
                  }
                </td>
                <td class="px-3 py-2" data-field="url">
                  @if (doc.url) {
                    <a [href]="doc.url" target="_blank" rel="noopener noreferrer"
                      class="text-blue-500 hover:underline">Ver</a>
                  } @else {
                    —
                  }
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }
  `,
})
export class ResultsTableComponent {
  readonly results = input<DocumentResult[]>([]);
  readonly expandedRows = signal<Set<number>>(new Set());

  severityBadgeClass(severity: string | null): string {
    switch (severity) {
      case 'H': return 'bg-red-100 text-red-700';
      case 'M': return 'bg-yellow-100 text-yellow-700';
      case 'L': return 'bg-green-100 text-green-700';
      default: return 'bg-gray-100 text-gray-500';
    }
  }

  relevanceBarColor(score: number): string {
    if (score >= 70) return 'bg-green-500';
    if (score >= 40) return 'bg-yellow-400';
    return 'bg-red-400';
  }

  toggleEvidence(index: number): void {
    const current = new Set(this.expandedRows());
    if (current.has(index)) {
      current.delete(index);
    } else {
      current.add(index);
    }
    this.expandedRows.set(current);
  }
}

// newsradar_front/src/components/results/ResultsTable.tsx
/**
 * ResultsTable — Displays search results in a table with CSV download button.
 *
 * Shared by ARAS and Riesgos pages. Generates CSV client-side for download.
 */
import React, { useCallback } from "react";
import type { DocumentResult } from "@/lib/api";

interface ResultsTableProps {
  results: DocumentResult[];
  excelUrl: string | null;
  totalDocuments: number;
  totalClassified: number;
}

/** Escape a value for CSV (wrap in quotes if it contains comma, newline, or quote). */
function csvEscape(val: string): string {
  if (val.includes(",") || val.includes("\n") || val.includes('"')) {
    return '"' + val.replace(/"/g, '""') + '"';
  }
  return val;
}

export default function ResultsTable({
  results,
  excelUrl,
  totalDocuments,
  totalClassified,
}: ResultsTableProps) {
  const handleDownload = useCallback(() => {
    const headers = [
      "Título",
      "Medio",
      "Fecha",
      "URL",
      "Resumen",
      "Categoría",
      "Severidad",
      "Evidencia",
    ];

    const rows = results.map((doc) => [
      csvEscape(doc.title),
      csvEscape(doc.source),
      csvEscape(doc.published_at ?? ""),
      csvEscape(doc.url ?? ""),
      csvEscape(doc.summary),
      csvEscape(doc.category ?? ""),
      csvEscape(doc.severity ?? ""),
      csvEscape(doc.evidence.slice(0, 3).join(" | ")),
    ]);

    const csv =
      "\uFEFF" + // BOM for Excel UTF-8
      headers.join(",") +
      "\n" +
      rows.map((r) => r.join(",")).join("\n");

    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `resultados_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }, [results]);

  if (results.length === 0) {
    return <p>Sin resultados para los criterios especificados.</p>;
  }

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "var(--spacing-md, 16px)" }}>
        <p style={{ margin: 0 }}>
          {totalDocuments} documentos encontrados, {totalClassified} clasificados.
        </p>
        <button
          type="button"
          onClick={handleDownload}
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "6px",
            padding: "8px 16px",
            backgroundColor: "#3fb950",
            color: "#fff",
            border: "none",
            borderRadius: "6px",
            cursor: "pointer",
            fontWeight: 500,
            fontSize: "14px",
          }}
        >
          📥 Descargar CSV
        </button>
      </div>

      {excelUrl && (
        <a
          href={excelUrl}
          download
          style={{
            display: "inline-block",
            marginBottom: "var(--spacing-sm, 8px)",
            color: "var(--blue, #3B82F6)",
          }}
        >
          📊 Descargar Excel (.xlsx)
        </a>
      )}

      <div style={{ maxHeight: "600px", overflowY: "auto", borderRadius: "8px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" }}>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Título</th>
              <th>Medio</th>
              <th>Fecha</th>
              <th>Categoría</th>
              <th>Severidad</th>
              <th>Evidencia</th>
              <th>URL</th>
            </tr>
          </thead>
          <tbody>
            {results.map((doc, idx) => (
              <tr key={idx}>
                <td>{idx + 1}</td>
                <td>{doc.title}</td>
                <td>{doc.source}</td>
                <td>{doc.published_at ?? "—"}</td>
                <td>{doc.category ?? "—"}</td>
                <td>
                  <span
                    style={{
                      fontWeight: 600,
                      color:
                        doc.severity === "H"
                          ? "#e53e3e"
                          : doc.severity === "M"
                            ? "#d69e2e"
                            : "#a0aec0",
                    }}
                  >
                    {doc.severity ?? "—"}
                  </span>
                </td>
                <td style={{ maxWidth: "300px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                  {doc.evidence.slice(0, 3).join(" | ") || "—"}
                </td>
                <td>
                  {doc.url ? (
                    <a href={doc.url} target="_blank" rel="noopener noreferrer">
                      Ver
                    </a>
                  ) : (
                    "—"
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
