// newsradar_front/src/app/UI/features/noticias/components/trendmap/momentum-bar.component.ts
import { Component, computed, input } from '@angular/core';
import * as d3 from 'd3';

const BAR_WIDTH = 120;
const BAR_HEIGHT = 10;

@Component({
  selector: 'app-momentum-bar',
  standalone: true,
  template: `
    <div class="flex items-center gap-2"
      [attr.aria-label]="label() ? label() + ': ' + pct() + '%' : 'Momentum: ' + pct() + '%'">
      @if (label()) {
        <span class="text-xs text-gray-500 whitespace-nowrap">{{ label() }}</span>
      }
      <svg [attr.width]="barWidth" [attr.height]="barHeight" role="progressbar"
        [attr.aria-valuenow]="pct()" aria-valuemin="0" aria-valuemax="100">
        <rect x="0" y="0" [attr.width]="barWidth" [attr.height]="barHeight"
          rx="3" fill="#E5E7EB" />
        <rect x="0" y="0" [attr.width]="fillWidth()" [attr.height]="barHeight"
          rx="3" fill="#4B5563" data-testid="momentum-fill" />
      </svg>
      <span class="text-xs font-medium text-gray-500 min-w-[32px] text-right" data-testid="momentum-pct">
        {{ pct() }}%
      </span>
    </div>
  `,
})
export class MomentumBarComponent {
  readonly value = input(0);
  readonly label = input<string | undefined>(undefined);

  readonly barWidth = BAR_WIDTH;
  readonly barHeight = BAR_HEIGHT;

  private readonly scale = d3.scaleLinear().domain([0, 1]).range([0, BAR_WIDTH]).clamp(true);

  readonly pct = computed(() => Math.round(Math.min(1, Math.max(0, this.value())) * 100));
  readonly fillWidth = computed(() => this.scale(Math.min(1, Math.max(0, this.value()))));
}

// newsradar_front/src/components/trendmap/MomentumBar.tsx
/**
 * MomentumBar — Visual progress bar for trend momentum (0–1 → 0–100%).
 *
 * Validates: Req 6.3 (momentum represented as percentage bar)
 */
import React from "react";

export interface MomentumBarProps {
  /** Momentum value between 0 and 1 */
  value: number;
  label?: string;
}

export default function MomentumBar({ value, label }: MomentumBarProps) {
  const pct = Math.round(Math.min(1, Math.max(0, value)) * 100);

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "var(--spacing-sm)",
      }}
      aria-label={label ? `${label}: ${pct}%` : `Momentum: ${pct}%`}
    >
      {label && (
        <span
          style={{
            fontSize: "var(--font-size-xs)",
            color: "var(--color-text-secondary)",
            whiteSpace: "nowrap",
          }}
        >
          {label}
        </span>
      )}
      <div
        role="progressbar"
        aria-valuenow={pct}
        aria-valuemin={0}
        aria-valuemax={100}
        style={{
          flex: 1,
          height: "8px",
          backgroundColor: "var(--color-surface-hover)",
          borderRadius: "var(--radius-sm)",
          overflow: "hidden",
          minWidth: "60px",
        }}
      >
        <div
          data-testid="momentum-fill"
          style={{
            width: `${pct}%`,
            height: "100%",
            backgroundColor: "var(--color-secondary)",
            borderRadius: "var(--radius-sm)",
            transition: "width var(--transition-normal)",
          }}
        />
      </div>
      <span
        data-testid="momentum-pct"
        style={{
          fontSize: "var(--font-size-xs)",
          fontWeight: "var(--font-weight-medium)",
          color: "var(--color-text-secondary)",
          minWidth: "32px",
          textAlign: "right",
        }}
      >
        {pct}%
      </span>
    </div>
  );
}
